engines:
  eslint:
    enabled: true
ratings:
  paths:
  - "**.js"
exclude_paths:
- coverage/
- build/
- node_modules/
- jasmine/spec/bundle.js
- jasmine/spec/bundle.js.map
- jasmine/lib/
- karma.conf.js
- src/libs/
- webpack.config.js
- LICENSE
- README.md
- package.json