language: node_js

node_js:
  - 6

before_script:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0

after_success:
  - cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js
